### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by Ali-Amir** [SauravKanchan/svelte-chartjs#100]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

The library doesn't provide proper types for properties of Chart component. Any chance this could be added?

### Describe the solution you'd like

Type definitions for properties to avoid errors like:
```
Type 'Chart<keyof ChartTypeRegistry, (number | Point | [number, number] | BubbleDataPoint | null)[], unknown>' is not assignable to type 'null | undefined'.
```

**Comment by dangreen** [comment]
@Ali-Amir Hi. Please try svelte-chartjs v3.1.2

**Comment by Ali-Amir** [comment]
@dangreen, wow, thanks for such a prompt update! Just tested and the issue is resolved.
