### ISSUE TITLE
Datalabels Plugin + Svelte Chart.js

### ISSUE THREAD

**Issue by Ncookiez** [SauravKanchan/svelte-chartjs#12]
Unsure if this is only an issue with this specific plugin, but I have had little success making it work for a long time...

I am trying to use chartjs-plugin-datalabels with svelte-chartjs. [Link to plugin](https://chartjs-plugin-datalabels.netlify.app/guide/getting-started.html)

I've tried running every version possible of the plugin, importing it through npm, CDN, different CDN providers, passing it as an array object, as normal with `plugins={chartDataLabels}` etc. with no success.

**Error:**
![image](https://user-images.githubusercontent.com/22108522/128431026-345c2df0-1bc5-4894-9c72-ff60c604a817.png)

I couldn't find any documentation on adding plugins through svelte-chartjs, so I'm going off of what I found while browsing the Base.svelte file and how it passes a reference of the chart to Chart.js.

I could really use some help or an alternative to what I've been doing wrongly.

**Comment by ruimgbarros** [comment]
Hi @Ncookiez, I'm also having some issues using plugins. Did you managed to do it? If so, could you provide an example?

**Comment by Ncookiez** [comment]
> Hi @Ncookiez, I'm also having some issues using plugins. Did you managed to do it? If so, could you provide an example?

Unfortunately not. I've since moved to Google Charts' API.

**Comment by ruimgbarros** [comment]
That's too bad... 
If anyone managed to solve the issue that could provide an example, I would be very grateful.
