### ISSUE TITLE
[Bug]: Install fails due to Svelte dependency

### ISSUE THREAD

**Issue by CAJazzer** [SauravKanchan/svelte-chartjs#126]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

  code ERESOLVE
  ERESOLVE unable to resolve dependency tree
 
  While resolving: chart@0.0.1
  Found: svelte@4.2.5
  node_modules/svelte
    dev svelte@"^4.0.5" from the root project
 
  Could not resolve dependency:
  peer svelte@"^3.45.0" from svelte-chartjs@3.1.2
  node_modules/svelte-chartjs
    svelte-chartjs@"*" from the root project
 

### Reproduction

npm i svelte-chartjs chart.js

### chart.js version

v4.4.0

### svelte-chartjs version

v3.1.2

**Comment by msjoshlopez** [comment]
Can confirm, I got this too when trying to add to a new project. What version is working or have you found out how to get around it?

**Comment by robhicks** [comment]
Is this project dead?

**Comment by niemyjski** [comment]
@SauravKanchan ^^

**Comment by niemyjski** [comment]
We're going to make sure this is fixed shortly, I want to get all open pr's closed before cutting a release and ensuring this is fixed.

**Comment by niemyjski** [comment]
This is fixed in the latest release https://github.com/SauravKanchan/svelte-chartjs/releases/tag/v3.1.4
