### ISSUE TITLE
[Bug]: Imports are broken after upgrade to 3.1.4

### ISSUE THREAD

**Issue by rkulinsky** [SauravKanchan/svelte-chartjs#143]
In 3.1.4 exports are broken:

```typescript
 import { Bar } from "svelte-chartjs";
```

> Error: Module '"svelte-chartjs"' has no exported member 'Bar'. (ts)

### Reproduction

Create new SvelteKit project.
Install svelte-chartjs version 3.1.4.
Add import from svelte-chartjs (as shown above) to one of your .svelte files.
Run `npm run svelte-check`.

### chart.js version

4.4.1

### svelte-chartjs version

3.1.4

### Possible solution

This amend to "exports" section of package.json fixes the issue (but I`m not 100% sure it is the right way of fixing this):
```json
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
     ...
    }
}
```

**Comment by dysfunc** [comment]
Hey @rkulinsky! Could you provide an example of what you're seeing using CodePen, CodeSandbox, or REPL? 

The library is working fine with the same config you specified:

https://codesandbox.io/p/devbox/dry-bush-xy24j5?embed=1

**Comment by npeeples** [comment]
![image](https://github.com/SauravKanchan/svelte-chartjs/assets/6862/eb961c1d-e10b-438b-9794-2f4c55f408d4)

@dysfunc Correct, the package still works, this is a typescript warning.

**Comment by rkulinsky** [comment]
@dysfunc 
I`m using Sveltekit. Sorry, I forgot to mention this issue is a result of "svelte-check" command.

Here is the link to the example:
[DevBox](https://codesandbox.io/p/devbox/adoring-frog-92xfnx?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls3gbqx100073b6i2xzxt4hl%2522%252C%2522sizes%2522%253A%255B54.46580313753152%252C45.53419686246848%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls3gbqx000023b6iuzp8735q%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls3gbqx000043b6i207cguce%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls3gbqx000063b6iic3u3t26%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B64.9775221260104%252C35.0224778739896%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls3gbqx000023b6iuzp8735q%2522%253A%257B%2522id%2522%253A%2522cls3gbqx000023b6iuzp8735q%2522%252C%2522activeTabId%2522%253A%2522cls456wm200023b6iwwamglco%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls3gbqwz00013b6i4l9yb6gg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cls456wm200023b6iwwamglco%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A87%252C%2522endLineNumber%2522%253A87%252C%2522startColumn%2522%253A29%252C%2522endColumn%2522%253A29%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Froutes%252F%252Bpage.svelte%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Froutes%252Fsverdle%252F%252Bpage.server.ts%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A60%252C%2522endLineNumber%2522%253A60%252C%2522startColumn%2522%253A24%252C%2522endColumn%2522%253A24%257D%255D%252C%2522id%2522%253A%2522cls45m66s00a83b6i8jmct34b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cls3gbqx000063b6iic3u3t26%2522%253A%257B%2522id%2522%253A%2522cls3gbqx000063b6iic3u3t26%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls3gbqx000053b6ia7kuamhr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cls3gbqx000053b6ia7kuamhr%2522%257D%252C%2522cls3gbqx000043b6i207cguce%2522%253A%257B%2522id%2522%253A%2522cls3gbqx000043b6i207cguce%2522%252C%2522activeTabId%2522%253A%2522cls45ycg000rd3b6if8n9wffc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls3gbqx000033b6i4rc8bmon%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522cls45ycg000rd3b6if8n9wffc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cls45ycma0040dcgpgl1jbfj9%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A22.71164046067787%257D)

(Look at the terminal output there or run `yarn svelte-check` in a new one).

**Comment by avi12** [comment]
I'm using Svelte in [Plasmo](/plasmohq/plasmo) and I'm experiencing the same issue

**Comment by dysfunc** [comment]
This was an oversight on my part from the last release. I fixed the type def path, and a PR is up for review.

**Comment by niemyjski** [comment]
I've pushed out a new release for this issue.

**Comment by rkulinsky** [comment]
> I've pushed out a new release for this issue.

Verified. The issue has gone away in my case.
