### ISSUE TITLE
Keep adding data

### ISSUE THREAD

**Issue by ruimgbarros** [SauravKanchan/svelte-chartjs#16]
Hi!

First of all, thank you very much for the work you have done here! This is great :) 

I'm having an issue that I'm not sure how to solve. I'm trying to add new data on select. How would you do that? 

Everytime I run the first select it works fine, but when I click the secound select I get the following error: 

"TypeError: cyclic object value"

Here's my code:

`<script>
  import Line from "svelte-chartjs/src/Line.svelte";

  let lines = [
    { label: "teste1", data: [65, 59, 80, 81, 56, 55, 40] },
    { label: "teste2", data: [100, 111, 1, 1, 1, 1, 11] },
  ];

  let selected;

  let data = {
    labels: ["January", "February", "March", "April", "May", "June", "July"],
    datasets: [],
  };

  function handleClick(values, a) {
    data.datasets.push(values);
    data.datasets = data.datasets;
  }
</script>

<select bind:value={selected} on:change={handleClick(selected)}>
  {#each lines as line}
    <option value={line}>
      {line.label}
    </option>
  {/each}
</select>

<div class="bg-yellow-300">
  {JSON.stringify(data)}
</div>

<Line {data} />

`

**Comment by Arantiryo** [comment]
Hey @ruimgbarros 👋 

Sorry for a late reply but is the issue still relevant for you with the version `2.0`? If so could you provide a minimal reproduction please? Thank you!
