### ISSUE TITLE
[Bug]: Compatibility with Svelte 5

### ISSUE THREAD

**Issue by GenieTim** [SauravKanchan/svelte-chartjs#168]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Svelte 5 was officially published. This library does not seemt to be compatible, in part due to following errors:

```
ERROR  Failed to compile with 3 errors10:46:18
error  in ./node_modules/svelte-chartjs/dist/utils/svelte.js10:46:18
export 'current_component' (imported as 'current_component') was not found in 'svelte/internal' (module has no exports)
error  in ./node_modules/svelte-chartjs/dist/utils/svelte.js10:46:18
export 'bubble' (imported as 'bubble') was not found in 'svelte/internal' (module has no exports)
error  in ./node_modules/svelte-chartjs/dist/utils/svelte.js10:46:18
export 'listen' (imported as 'listen') was not found in 'svelte/internal' (module has no exports)
```

### Reproduction

https://github.com/SauravKanchan/svelte-chartjs

### chart.js version

v4.4.6

### svelte-chartjs version

v3.1.5

### Possible solution

I guess this library has to be updated to use $runes now.
The corresponding event functionality is pretty simplified, if I understood correctly, so the update should be doable. If nobody is working on it already, I could help draft a PR.

**Comment by Crazytieguy** [comment]
I think only [this](https://github.com/SauravKanchan/svelte-chartjs/blob/4333128d3f47b7e8c9a7a77177ad8592c2e22999/src/utils/svelte.ts#L6) file needs to be fixed, since it uses `svelte/internal`. Migrating to runes shouldn't be needed for the library to function

**Comment by GenieTim** [comment]
I'll close this, as I realised that it's in principle a duplicate of #158 and #167
