### ISSUE TITLE
Upgrade to 1.1.0 broke existing charts

### ISSUE THREAD

**Issue by obendi** [SauravKanchan/svelte-chartjs#17]
Hi,

I upgraded from 1.0.1 to 1.1.0 and all charts are broken. Looks like all parameters passed in options has no effect. Parameters like:

- tooltips
- legends
- scales

Is it a bug or I have to consider some changes in the way I use svelte-chartjs in this new version (1.1.0).

Thanks!

**Comment by Mikk36** [comment]
Could this be because svelte-chartjs upgraded to ChartJS v3 with 1.1.0?

**Comment by Lirben** [comment]
Having the same problem over here. I also upgraded chartJS to vs 3.

**Comment by ferulisses** [comment]
Took me a while to figure this out, ChartJS break some compatibilities when upgrading from 2.9 to 3.x, so, the previous charts created won't work anymore, and the demo from svelte-chartjs is also out of date.

One change that get me was the title declaration, on svelte-chartjs@1.0.1 with ChartJS@2.9.4:
```
let options = {
   title: {
      display: true,
      text: 'My Title'
   }
}
```

After upgrade to svelte-chartjs@1.1.4 with ChartJS@3.7.1:
```
let options = {
   plugins: {
      title: {
         display: true,
         text: 'My Title'
      }
   }
}
```

There are several changes, all documented:

> - legend, title and tooltip namespaces were moved from options to options.plugins.
> - tooltips.custom was renamed to plugins.tooltip.external

You can check it here:
https://www.chartjs.org/docs/master/getting-started/v3-migration.html
