### ISSUE TITLE
How do I add a date adapter?

### ISSUE THREAD

**Issue by 6peterlu** [SauravKanchan/svelte-chartjs#21]
I get
```
Error: This method is not implemented: Check that a complete date adapter is provided.
```
when following the steps at https://github.com/chartjs/chartjs-adapter-luxon.

Thank you!

**Comment by Arantiryo** [comment]
Looks like date adapters work as expected with version `2.0`. Here's [an example](https://codesandbox.io/s/intelligent-haslett-di33zj?file=/components/Chart.svelte:88-119) with `chartjs-adapter-luxon`.
