### ISSUE TITLE
Chart Interactions

### ISSUE THREAD

**Issue by bmccorm2** [SauravKanchan/svelte-chartjs#24]
Hello - love your package!  any plans to implement chart interactions in the future?  (i.e., getElementsAtEventForMode)

**Comment by Arantiryo** [comment]
Hi @bmccorm2 👋 

Chart interactions are now implemented in [v2.1.0](https://github.com/SauravKanchan/svelte-chartjs/releases/tag/v2.1.0)! You can find a code sandbox with example usage [here](https://codesandbox.io/s/github/SauravKanchan/svelte-chartjs/tree/master/sandboxes/events?file=/components/Chart.svelte).
