### ISSUE TITLE
HorizontalBar not working

### ISSUE THREAD

**Issue by cbajohr** [SauravKanchan/svelte-chartjs#27]
This is more like a hint, than an Issue...

The HorizontalBar isn't working. I've checked the svelte code and as far as I can see the "horizontalBar" type does not exist on the current chartjs version. Maybe I'm getting it wrong, but I didn't get it to work with the HorizontalBar Component.
The only difference between bar and horizontalBar is an option to set the axis:
 
```
const config = {
  type: 'bar',
  data,
  options: {
    indexAxis: 'y',
  }
};
```
(https://www.chartjs.org/docs/latest/charts/bar.html#horizontal-bar-chart)

**Comment by Arantiryo** [comment]
Hi @cbajohr !

`HorizontalBar` component was recently removed and as you mention the way to implement a horizontal bar chart is to use a regular bar chart and set `indexAxis` option to `'y'`.

**Comment by athanhat** [comment]
Hi @Arantiryo that works but there is a problem with the type of options for example

```typescript
<script lang='ts'>
// @ts-nocheck

const options = {
        responsive: true,
        maintainAspectRatio: false,
        indexAxis: 'y' }
</script>

<article>
    <Bar {options} />
</article>

<!--
Type '{ responsive: boolean; maintainAspectRatio: boolean; indexAxis: string; }' is not assignable to type '_DeepPartialObject<CoreChartOptions<"bar"> & ElementChartOptions<"bar"> & PluginChartOptions<"bar"> & DatasetChartOptions<"bar"> & ScaleChartOptions<...> & BarControllerChartOptions>'.
  Types of property 'indexAxis' are incompatible.
    Type 'string' is not assignable to type '"y" | "x" | undefined'
-->
```
It would be nice if that can be resolved by specifying the correct type for the moment  a quick fix is
`@ts-nocheck` to disable typescript checking for this svelte file
