### ISSUE TITLE
Pie chart dissapears on data update

### ISSUE THREAD

**Issue by dillon-co** [SauravKanchan/svelte-chartjs#35]
I have a pie chart whos data is the value of a few input sliders. When the sliders change the pie chart dissapears. 

Is this a bug or something I'm missing?

`  const handleSliderChange = () => {
    pieChartData = { datasets: [
          {
            data: [sliderA, sliderB, sliderC],
            backgroundColor: ['rgb(255, 99, 132)',
                            'rgb(54, 162, 235)',
                            'rgb(255, 205, 86)']
          }
        ]
      };
      pieChartData = pieChartData;
  }`

**Comment by Arantiryo** [comment]
Hi @dillon-co 👋 

Have you checked if the issue persists in the latest version (`2.0.1`)? If so would you be able to fork [this example](https://codesandbox.io/s/github/SauravKanchan/svelte-chartjs/tree/master/sandboxes/pie) and provide a minimal reproduction? 

Thank you!
