### ISSUE TITLE
Help with a certain feature

### ISSUE THREAD

**Issue by SekSion** [SauravKanchan/svelte-chartjs#61]
Hey, i'm having an issue with chartdatalabels where i need them outside of the bar and i want to give a space  between the end of chart and the bar itself, i find on the documentation something called grace, but i am not being able to use it with svelte-js, 

I updated it to v2 right now hoping it would work but still nothing am i missing something?

![image](https://user-images.githubusercontent.com/46030872/183102819-e8bff503-4938-4337-89f3-c25169e62e9a.png)
![image](https://user-images.githubusercontent.com/46030872/183102867-9657747d-28bf-4fe4-84ed-dd9957f8e8c7.png)
![image](https://user-images.githubusercontent.com/46030872/183102938-0aacc198-375f-47f9-b1c1-aa2648806c84.png)

**Comment by Arantiryo** [comment]
Hi @SekSion 👋 

Thank you for the detailed explanation! I've tried recreating the issue but `grace` seems to work just fine in my case. Here's a [code sandbox](https://codesandbox.io/s/restless-cache-6e6265?file=/components/Chart.svelte), you can uncomment `// grace: "20%"` to see that it works.

Could you modify the example to see if you can reproduce the problem?

Thanks!

**Comment by SekSion** [comment]
Hi @Arantiryo Thx for the reply

Ye it seems i deleted the node_modules and installed the same chart js version, i was using 3.9.1 and you had 3.8.0 on the example, and tried again and it worked, something happened but it seems i can use it now, thx!
