### ISSUE TITLE
Can't get imports to work with latest SvelteKit/Vite

### ISSUE THREAD

**Issue by Shackless** [SauravKanchan/svelte-chartjs#67]
This might be more of a chart.js issue but is there a demo for use in latest (post-vite.config.js) SvelteKit? I tried all of the following: 

```
import { Radar } from 'svelte-chartjs';
import { Chart as ChartJS, LineElement, RadialLinearScale, PointElement } from 'chart.js';

ChartJS.register(LineElement, RadialLinearScale, PointElement);
```

which gives me `Named export 'Chart' not found. The requested module 'chart.js' is a CommonJS module, which may not support all module.exports as named exports.`.

This does not work either: 

```ts
import ChartJS, { LineElement, RadialLinearScale, PointElement } from 'chart.js';
```

Then I tried 

```ts
import { Radar } from 'svelte-chartjs'
import 'chart.js/auto';
``` 

giving me `Directory import 'my-path/chart.js/auto' is not supported resolving ES modules imported from...`.

I also tried 

```ts
import { Chart, registerables } from 'chart.js/dist/chart.esm';
Chart.register(...registerables);

import { Tooltip } from 'chart.js/dist/chart.esm';
```

giving me ![image](https://user-images.githubusercontent.com/306996/186355460-60130c75-79a3-4ea8-96dc-4f8c22bb6dc8.png)

package.json:

```json
"@sveltejs/kit": "1.0.0-next.428",
"svelte-chartjs": "^2.1.0",
"vite": "^3.0.0"
```

**Comment by Shackless** [comment]
I asked in the SvelteKit Discord for help and people tell me the problem is that svelte-chartjs should change its internal imports to the ChartJS ESM module, so for example https://github.com/SauravKanchan/svelte-chartjs/blob/f190069eba3bd3d16c23eea4c21f14c5b29f38bd/src/Radar.svelte#L3 

should be `import { Chart as ChartJS, RadarController } from 'chart.js/dist/chart.esm;`

What's your take on this, @SauravKanchan?

**Comment by dangreen** [comment]
@Shackless Hi. It's known issue of Chart.js, which will be fixed in v4.

https://github.com/chartjs/Chart.js/issues/9436
https://github.com/chartjs/Chart.js/pull/10584

**Comment by Shackless** [comment]
Ah thanks, I'll close my issue then. Maybe it's worth mentioning in the README here until v4 is released.

**Comment by suda** [comment]
Is there any workaround until the release of Chart.js 4?
