### ISSUE TITLE
Bar component requires chart property but it still works fine without it.

### ISSUE THREAD

**Issue by topazrn** [SauravKanchan/svelte-chartjs#69]
Bar component requires chart property
![image](https://user-images.githubusercontent.com/40129033/187010159-c31ad728-bd15-4dc9-8066-cf8be46238fd.png)
The chart works even with this error.
But I don't like having red squiggly lines in my code, how should I clean this error?
I tried putting in the chart property, but I don't know what should be inside the chart property.
![image](https://user-images.githubusercontent.com/40129033/187010282-659be016-ff57-4ac6-a430-81cbf54726b9.png)

After reading the [source code](https://github.com/SauravKanchan/svelte-chartjs/blob/master/src/Bar.svelte#L10), it seems chart can be null, but it's still giving me the error
![image](https://user-images.githubusercontent.com/40129033/187010511-09d35064-b9a7-4cd6-9470-f82079c1e7a6.png)

Does anyone have any suggestion? Maybe making the chart property optional is a good idea?

**Comment by dangreen** [comment]
@topazrn Hi. Please try [v2.1.1](https://github.com/SauravKanchan/svelte-chartjs/releases/tag/v2.1.1)

**Comment by topazrn** [comment]
Beautiful!
