### ISSUE TITLE
[Bug]: The type: scales.x.type isn't defined in TypeScript

### ISSUE THREAD

**Issue by Coreusa** [SauravKanchan/svelte-chartjs#83]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Here's an excerpt of an example code that shows this error in VS Code:

```
<script>
let chartOptions = {
    showTooltips: true,
    hover: {
      intersect: true
    },
    animation: {
      duration: 0,
    },
    plugins: {
      legend: {
        display: true,
        labels: {
          color: '#fff',
          font: {
            size: 18
          }
        }
      }
    },
    scales: {
      x: {
        type: 'linear', **<-- This causes the error, see below**
        title: {
          display: true,
          text: `Example`,
          color: '#aaa',
          font: {
            size: 18
          }
        },
        alignToPixels: true,
        grid: {
          color: '#555',
          type: 'dashed',
        },
        ticks: {
          stepSize: 5
        }
      },
      y: {
        title: {
          display: true,
          text: 'Example',
          color: '#aaa',
          font: {
            size: 18
          }
        },
        ticks: {
          stepSize: 20,
          display: true
        },
        min: -200,
        max: 0,
        grid: {
          color: '#555'
        }
      }
    }
  }
</script>
```

Then for the HTML markup
```
<div>
    <Line
      data="{chartData}"
      options="{chartOptions}"
    />
  {/if}
</div>
```

VS Code then shows this error:
![image](https://user-images.githubusercontent.com/706874/200523395-eb3aca7e-21b9-4fe8-936c-9af07e0e8ad5.png)

![image](https://user-images.githubusercontent.com/706874/200525527-bbf90236-45c2-497a-8b0d-d707c7b857eb.png)

> (property) options?: _DeepPartialObject<CoreChartOptions<"line"> & ElementChartOptions<"line"> & PluginChartOptions<"line"> & DatasetChartOptions<"line"> & ScaleChartOptions<...> & LineControllerChartOptions>
> Type '{ showTooltips: boolean; hover: { intersect: boolean; }; animation: { duration: number; }; plugins: { tooltip: { callbacks: { title: (data: any) => string; label: (data: any) => string; }; }; legend: { display: boolean; labels: { ...; }; }; }; scales: { ...; }; }' is not assignable to type '_DeepPartialObject<CoreChartOptions<"line"> & ElementChartOptions<"line"> & PluginChartOptions<"line"> & DatasetChartOptions<"line"> & ScaleChartOptions<...> & LineControllerChartOptions>'.
>   Types of property 'scales' are incompatible.
>     Type '{ x: { type: string; title: { display: boolean; text: string; color: string; font: { size: number; }; }; min: number; max: number; alignToPixels: boolean; grid: { color: string; type: string; }; ticks: { stepSize: number; }; }; y: { ...; }; }' is not assignable to type '_DeepPartialObject<{ [key: string]: ScaleOptionsByType<keyof CartesianScaleTypeRegistry>; }>'.
>       Property 'x' is incompatible with index signature.
>         Type '{ type: string; title: { display: boolean; text: string; color: string; font: { size: number; }; }; min: number; max: number; alignToPixels: boolean; grid: { color: string; type: string; }; ticks: { stepSize: number; }; }' is not assignable to type '_DeepPartialObject<{ type: "linear"; } & CartesianScaleOptions & { beginAtZero: boolean; suggestedMin?: number; suggestedMax?: number; grace?: string | number; ticks: { format: NumberFormatOptions; precision: number; stepSize: number; count: number; }; }> | _DeepPartialObject<...> | _DeepPartialObject<...> | _DeepPa...'.
>           Type '{ type: string; title: { display: boolean; text: string; color: string; font: { size: number; }; }; min: number; max: number; alignToPixels: boolean; grid: { color: string; type: string; }; ticks: { stepSize: number; }; }' is not assignable to type '_DeepPartialObject<{ type: "timeseries"; } & Omit<CartesianScaleOptions, "min" | "max"> & { min: string | number; max: string | number; suggestedMin: string | number; ... 5 more ...; ticks: { ...; }; }>'.
>             Types of property 'type' are incompatible.
>               Type 'string' is not assignable to type '"timeseries"'.ts(2322)

If I remove the scales.x.type.linear attribute, the error disappears.

![image](https://user-images.githubusercontent.com/706874/200523864-1406c71e-032f-427d-b071-4577246b7672.png)

### Reproduction

Code is available in the text

### chart.js version

v3.5.0

### svelte-chartjs version

v3.0.1

### Possible solution

Add the type definition for the x.scales.linear attribute

**Comment by dangreen** [comment]
@Coreusa Hi. You should set type to options object

```ts
import type { ChartOptions } from 'chart.js'

let chartOptions: ChartOptions<'line'> = ...
```

or use `as const`

```ts
type: 'linear' as const
```
