### ISSUE TITLE
[Bug]: legend.display = false not working

### ISSUE THREAD

**Issue by yoh-extradat** [SauravKanchan/svelte-chartjs#90]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

After setting legend.display to false, the legend is still rendered.

```html
<Bar options={{plugins:{legend: {display: true}}}} {data} />
```

### Reproduction

see above

### chart.js version

v3.1.0

### svelte-chartjs version

v4.0.1

**Comment by dangreen** [comment]
@yoh-extradat Hi. I tried to reproduce it, but it looks like all works: https://codesandbox.io/s/autumn-sun-xhli2l?file=/components/Chart.svelte
