### ISSUE TITLE
Chart not displaying unless hot reloading

### ISSUE THREAD

**Issue by Kattenelvis** [SauravKanchan/svelte-chartjs#94]
### Current and expected behavior

If I save my .svelte file such that vite's hot reload happends, then the Pie chart shows up. But otherwise it's just a white box. 

```
<script lang="ts">
import { Pie } from 'svelte-chartjs';
import { Chart as ChartJS, Title, Tooltip, Legend, ArcElement, CategoryScale } from 'chart.js';

ChartJS.register(Title, Tooltip, Legend, CategoryScale, ArcElement);

export let votes: number[] = [1, 2, 3],
	labels: string[] = ['1', '2', '3'];

const data = {
labels,
datasets: [
	{
		label: 'Results',
		fill: true,
		backgroundColor: ['#0157BE', '#9333EA', '#93C5FD', '#D8B4FE'],
		borderColor: ['#FFFFFF'],
		data: votes
	}
]
};

      </script>

      <Pie {data} options={{ responsive: true }} />
```

### Reproduction

Can't reproduce it

### chart.js version

4.0.1

### svelte-chartjs version

3.1.0

### Possible solution

OnMount() does not work to resolve the bug

**Comment by dangreen** [comment]
@Kattenelvis Hi. Without reproduction we can't debug code and find the problem.

**Comment by flowhl** [comment]
Hi I have had the same issue today. Would you mind taking a look at my svelte file?
Using SvelteKit and I'm not very experienced in web developement so It could be a beginner issue. Could you take a look at this: Its in src/routes/testing/+page.js
[weatherapp-bug-chartjs.zip](https://github.com/SauravKanchan/svelte-chartjs/files/10254322/weatherapp-bug-chartjs.zip)

![image](https://user-images.githubusercontent.com/50335799/208310705-72244c7f-cacd-4913-b444-74f334a69b94.png)

**Comment by dangreen** [comment]
@flowhl Hi. Just remove `style="display: contents"` from chart container and all will work.

**Comment by Kattenelvis** [comment]
It did not help my issue

**Comment by dangreen** [comment]
@Kattenelvis Without reproduction we can't debug code and find the problem.

**Comment by dangreen** [comment]
Closed due to inactivity
