### ISSUE TITLE
[Bug]:  Everything works on dev but as soon as I build doesn't work in a router

### ISSUE THREAD

**Issue by PabloRuizCuevas** [SauravKanchan/svelte-chartjs#98]
### Would you like to work on a fix?

- [X] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

In a sveltekit project where everything works in dev, the charts seems not to be working when build at routed pages.

In specific charts.js is working in dev well, but is not working in a routed page `/page `when the it is build for production.

It is hard to debug as there is no error messages, but there are significantly less `GET `request when going to /page and if I go to the main page and then use a `<a/>` link to the route, everything works fine.

What could be the reason behind this? Am I missing some configuration of sveltkit ? or it is a problem of this library?

the component looks like this:
```

<script lang="ts">
  import { Doughnut } from 'svelte-chartjs';
  export datax = 10
  export datay = 20

  import {
    Chart as ChartJS,
    Title,
    Tooltip,
    Legend,
    ArcElement,
    CategoryScale,
  } from 'chart.js'


  let chart: Doughnut;
  let data = {
      labels: ['Pension', 'Monthly paid out salary', 'Tax Under', 'Tax Over'],
    datasets: [
      {
      label: 'Danish Kronws',
      data: [datax , datay],
      backgroundColor: [
        'rgba(255, 134,159,0.4)',
        'rgba(98,  182, 239,0.4)',
      ],
      borderWidth: 2,
      borderColor: [
        'rgba(255, 134, 159, 1)',
        'rgba(98,  182, 239, 1)',
      ],
      },
    ],
  };

  ChartJS.register(Title, Tooltip, Legend, ArcElement, CategoryScale);

  $: {if (chart) {
      chart.data.datasets[0].data = [datax ,datay]
    }
  }

</script>

<div class="chart">
  <Doughnut bind:chart data={data} options={options} />

</div>

<style>
  .chart{
    border-radius: 10px;
    box-shadow:0 0 15px 4px rgba(0,0,0,0.06);
    padding: 10px;
    width: 600px;
  }

</style>
```

### Reproduction

 http://74.208.40.117:5173  (click log in) vs  direct to http://74.208.40.117:5173/dashboard  (not works)

### chart.js version

4.1.1

### svelte-chartjs version

3.1.0

### Possible solution

I tried many things already like changing the ssr or putting onMount, i think it may be related to that or maybe to "vite preview"

**Comment by dangreen** [comment]
@PabloRuizCuevas Hi. Please provide repo with minimal issue reproduction.

**Comment by PabloRuizCuevas** [comment]
Sure, here I try both donut and bar plot and just added some sliders to edit the data:

https://github.com/PabloRuizCuevas/webapp-seren

And mostly the same (many commits after, so it is not anymore minimal) but the error is the same and on the other hand is already hosted ( and with newer versions):
"http://74.208.40.117:5173/dashboard" doesn't work but  " http://74.208.40.117:5173" and then go to dashboard internally it does.

Just to clarify again that the npm run dev works perfectly  but it is hosted now using "npm run build" and "preview"

Thanks in advance.

**Comment by dangreen** [comment]
@PabloRuizCuevas Hi.

You are disabled JS for dashboard here:

https://github.com/PabloRuizCuevas/webapp-seren/blob/16287140a7b14abc17ed5078890899ca238aff71/src/routes/dashboard/%2Bpage.ts#L4-L6
